services:
  ca-server:
    image: smallstep/step-ca
    container_name: ca-server
    env_file:
      - .env
    ports:
      - "8443:8443"
      - "9000:9000"
    command: sh -c step ca init

    volumes:
      - step:/home/step

  vpn-server:
    build: vpn-server/
    ports:
      - "443:443"

volumes:
  step:


