FROM alpine:latest
#RUN apk update
#RUN apk upgrade

# Dependencies
RUN apk add openvpn step-cli ufw ip6tables openrc openssl

# Configure step client 
RUN mkdir step-dir
RUN ln -s /usr/share/step-dir /step-dir
RUN chmod 700 /step-dir
WORKDIR /step-dir 

# Configure OpenVPN
RUN openvpn --genkey --secret ta.key
#RUN openssl dhparam -out dh2048.pem 2048
COPY server.conf /etc/openvpn/server.conf

# Configure routing and firewall
RUN ip route list default
RUN echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
COPY before.rules /etc/ufw/before.rules
RUN ufw allow 1194/udp
RUN ufw allow ssh
#RUN ufw enable
RUN echo 'DEFAULT_FORWARD_POLICY="ACCEPT"' >> /etc/default/ufw

# Start services
RUN rc-update add openvpn
#RUN rc-service openvpn start
RUN cp ta.key /etc/openvpn/server




